language: generic 

services:
  - docker

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: "my-first-app"
  env: "myfirstapp-env"

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  bucket_name: "ajit-first-app-bucket"
  bucket_path: "docker"

  on:
    branch: main